// COMPANY
export const HTTP_COMPANY_FETCHING = "HTTP_COMPANY_FETCHING";
export const HTTP_COMPANY_FAILED = "HTTP_COMPANY_FAILED";
export const HTTP_COMPANY_SUCCESS = "HTTP_COMPANY_SUCCESS";
export const HTTP_COMPANY_CLEAR = "HTTP_COMPANY_CLEAR";

// WAREHOUSE
export const HTTP_WAREHOUSE_FETCHING = "HTTP_WAREHOUSE_FETCHING";
export const HTTP_WAREHOUSE_FAILED = "HTTP_WAREHOUSE_FAILED";
export const HTTP_WAREHOUSE_SUCCESS = "HTTP_WAREHOUSE_SUCCESS";
export const HTTP_WAREHOUSE_CLEAR = "HTTP_WAREHOUSE_CLEAR";

// BU
export const HTTP_BU_FETCHING = "HTTP_BU_FETCHING";
export const HTTP_BU_FAILED = "HTTP_BU_FAILED";
export const HTTP_BU_SUCCESS = "HTTP_BU_SUCCESS";
export const HTTP_BU_CLEAR = "HTTP_BU_CLEAR";

// DEPARTMENT
export const HTTP_DEPARTMENT_FETCHING = "HTTP_DEPARTMENT_FETCHING";
export const HTTP_DEPARTMENT_FAILED = "HTTP_DEPARTMENT_FAILED";
export const HTTP_DEPARTMENT_SUCCESS = "HTTP_DEPARTMENT_SUCCESS";
export const HTTP_DEPARTMENT_CLEAR = "HTTP_DEPARTMENT_CLEAR";

// COSTCENTER
export const HTTP_COSTCENTER_FETCHING = "HTTP_COSTCENTER_FETCHING";
export const HTTP_COSTCENTER_FAILED = "HTTP_COSTCENTER_FAILED";
export const HTTP_COSTCENTER_SUCCESS = "HTTP_COSTCENTER_SUCCESS";
export const HTTP_COSTCENTER_CLEAR = "HTTP_COSTCENTER_CLEAR";

// APPROVE
export const HTTP_APPROVE_FETCHING = "HTTP_APPROVE_FETCHING";
export const HTTP_APPROVE_FAILED = "HTTP_APPROVE_FAILED";
export const HTTP_APPROVE_SUCCESS = "HTTP_APPROVE_SUCCESS";
export const HTTP_APPROVE_CLEAR = "HTTP_APPROVE_CLEAR";

// FINALAPPROVE
export const HTTP_FINALAPPROVE_FETCHING = "HTTP_FINALAPPROVE_FETCHING";
export const HTTP_FINALAPPROVE_FAILED = "HTTP_FINALAPPROVE_FAILED";
export const HTTP_FINALAPPROVE_SUCCESS = "HTTP_FINALAPPROVE_SUCCESS";
export const HTTP_FINALAPPROVE_CLEAR = "HTTP_FINALAPPROVE_CLEAR";

// BUYER
export const HTTP_BUYER_FETCHING = "HTTP_BUYER_FETCHING";
export const HTTP_BUYER_FAILED = "HTTP_BUYER_FAILED";
export const HTTP_BUYER_SUCCESS = "HTTP_BUYER_SUCCESS";
export const HTTP_BUYER_CLEAR = "HTTP_BUYER_CLEAR";

// ITEM
export const HTTP_ITEM_FETCHING = "HTTP_ITEM_FETCHING";
export const HTTP_ITEM_FAILED = "HTTP_ITEM_FAILED";
export const HTTP_ITEM_SUCCESS = "HTTP_ITEM_SUCCESS";
export const HTTP_ITEM_CLEAR = "HTTP_ITEM_CLEAR";

// ITEMDETAIL
export const HTTP_ITEMDETAIL_FETCHING = "HTTP_ITEMDETAIL_FETCHING";
export const HTTP_ITEMDETAIL_FAILED = "HTTP_ITEMDETAIL_FAILED";
export const HTTP_ITEMDETAIL_SUCCESS = "HTTP_ITEMDETAIL_SUCCESS";
export const HTTP_ITEMDETAIL_CLEAR = "HTTP_ITEMDETAIL_CLEAR";

// ITEMUNIT
export const HTTP_ITEMUNIT_FETCHING = "HTTP_ITEMUNIT_FETCHING";
export const HTTP_ITEMUNIT_FAILED = "HTTP_ITEMUNIT_FAILED";
export const HTTP_ITEMUNIT_SUCCESS = "HTTP_ITEMUNIT_SUCCESS";
export const HTTP_ITEMUNIT_CLEAR = "HTTP_ITEMUNIT_CLEAR";

// PHGROUP
export const HTTP_PHGROUP_FETCHING = "HTTP_PHGROUP_FETCHING";
export const HTTP_PHGROUP_FAILED = "HTTP_PHGROUP_FAILED";
export const HTTP_PHGROUP_SUCCESS = "HTTP_PHGROUP_SUCCESS";
export const HTTP_PHGROUP_CLEAR = "HTTP_PHGROUP_CLEAR";

// PHBUYER
export const HTTP_PHBUYER_FETCHING = "HTTP_PHBUYER_FETCHING";
export const HTTP_PHBUYER_FAILED = "HTTP_PHBUYER_FAILED";
export const HTTP_PHBUYER_SUCCESS = "HTTP_PHBUYER_SUCCESS";
export const HTTP_PHBUYER_CLEAR = "HTTP_PHBUYER_CLEAR";

// SUPPLIER
export const HTTP_SUPPLIER_FETCHING = "HTTP_SUPPLIER_FETCHING";
export const HTTP_SUPPLIER_FAILED = "HTTP_SUPPLIER_FAILED";
export const HTTP_SUPPLIER_SUCCESS = "HTTP_SUPPLIER_SUCCESS";
export const HTTP_SUPPLIER_CLEAR = "HTTP_SUPPLIER_CLEAR";

// Login Page
export const HTTP_LOGIN_FETCHING = "HTTP_LOGIN_FETCHING";
export const HTTP_LOGIN_FAILED = "HTTP_LOGIN_FAILED";
export const HTTP_LOGIN_SUCCESS = "HTTP_LOGIN_SUCCESS";
export const HTTP_LOGIN_LOGOUT = "HTTP_LOGIN_LOGOUT";

// PRNUMBER
export const HTTP_PRNUMBER_FETCHING = "HTTP_PRNUMBER_FETCHING";
export const HTTP_PRNUMBER_FAILED = "HTTP_PRNUMBER_FAILED";
export const HTTP_PRNUMBER_SUCCESS = "HTTP_PRNUMBER_SUCCESS";
export const HTTP_PRNUMBER_CLEAR = "HTTP_PRNUMBER_CLEAR";

// PRNUMBERBUYER
export const HTTP_PRNUMBERBUYER_FETCHING = "HTTP_PRNUMBERBUYER_FETCHING";
export const HTTP_PRNUMBERBUYER_FAILED = "HTTP_PRNUMBERBUYER_FAILED";
export const HTTP_PRNUMBERBUYER_SUCCESS = "HTTP_PRNUMBERBUYER_SUCCESS";
export const HTTP_PRNUMBERBUYER_CLEAR = "HTTP_PRNUMBERBUYER_CLEAR";

// PRHEAD
export const HTTP_PRHEAD_FETCHING = "HTTP_PRHEAD_FETCHING";
export const HTTP_PRHEAD_FAILED = "HTTP_PRHEAD_FAILED";
export const HTTP_PRHEAD_SUCCESS = "HTTP_PRHEAD_SUCCESS";
export const HTTP_PRHEAD_CLEAR = "HTTP_PRHEAD_CLEAR";

// PRHEADAPPROVE
export const HTTP_PRHEADAPPROVE_FETCHING = "HTTP_PRHEADAPPROVE_FETCHING";
export const HTTP_PRHEADAPPROVE_FAILED = "HTTP_PRHEADAPPROVE_FAILED";
export const HTTP_PRHEADAPPROVE_SUCCESS = "HTTP_PRHEADAPPROVE_SUCCESS";
export const HTTP_PRHEADAPPROVE_CLEAR = "HTTP_PRHEADAPPROVE_CLEAR";

// PRDETAIL
export const HTTP_PRDETAIL_FETCHING = "HTTP_PRDETAIL_FETCHING";
export const HTTP_PRDETAIL_FAILED = "HTTP_PRDETAIL_FAILED";
export const HTTP_PRDETAIL_SUCCESS = "HTTP_PRDETAIL_SUCCESS";
export const HTTP_PRDETAIL_CLEAR = "HTTP_PRDETAIL_CLEAR";

// PRDETAILBUYER
export const HTTP_PRDETAILBUYER_FETCHING = "HTTP_PRDETAILBUYER_FETCHING";
export const HTTP_PRDETAILBUYER_FAILED = "HTTP_PRDETAILBUYER_FAILED";
export const HTTP_PRDETAILBUYER_SUCCESS = "HTTP_PRDETAILBUYER_SUCCESS";
export const HTTP_PRDETAILBUYER_CLEAR = "HTTP_PRDETAILBUYER_CLEAR";

// PRCONFIRMBUYER
export const HTTP_PRCONFIRMBUYER_FETCHING = "HTTP_PRCONFIRMBUYER_FETCHING";
export const HTTP_PRCONFIRMBUYER_FAILED = "HTTP_PRCONFIRMBUYER_FAILED";
export const HTTP_PRCONFIRMBUYER_SUCCESS = "HTTP_PRCONFIRMBUYER_SUCCESS";
export const HTTP_PRCONFIRMBUYER_CLEAR = "HTTP_PRCONFIRMBUYER_CLEAR";

// PRCONFIRM
export const HTTP_PRCONFIRM_FETCHING = "HTTP_PRCONFIRM_FETCHING";
export const HTTP_PRCONFIRM_FAILED = "HTTP_PRCONFIRM_FAILED";
export const HTTP_PRCONFIRM_SUCCESS = "HTTP_PRCONFIRM_SUCCESS";
export const HTTP_PRCONFIRM_CLEAR = "HTTP_PRCONFIRM_CLEAR";

// MONTH
export const HTTP_MONTH_FETCHING = "HTTP_MONTH_FETCHING";
export const HTTP_MONTH_FAILED = "HTTP_MONTH_FAILED";
export const HTTP_MONTH_SUCCESS = "HTTP_MONTH_SUCCESS";
export const HTTP_MONTH_CLEAR = "HTTP_MONTH_CLEAR";

// STATUS
export const HTTP_STATUS_FETCHING = "HTTP_STATUS_FETCHING";
export const HTTP_STATUS_FAILED = "HTTP_STATUS_FAILED";
export const HTTP_STATUS_SUCCESS = "HTTP_STATUS_SUCCESS";
export const HTTP_STATUS_CLEAR = "HTTP_STATUS_CLEAR";

// Stock Edit Page
export const HTTP_STOCK_EDIT_FETCHING = "HTTP_STOCK_EDIT_FETCHING";
export const HTTP_STOCK_EDIT_SUCCESS = "HTTP_STOCK_EDIT_SUCCESS";
export const HTTP_STOCK_EDIT_FAILED = "HTTP_STOCK_EDIT_FAILED";
export const HTTP_STOCK_EDIT_INITIALED = "HTTP_STOCK_EDIT_INITIALED";

// Transaction Edit Page
export const HTTP_TRANSACTION_FETCHING = "HTTP_TRANSACTION_FETCHING";
export const HTTP_TRANSACTION_SUCCESS = "HTTP_TRANSACTION_SUCCESS";
export const HTTP_TRANSACTION_FAILED = "HTTP_TRANSACTION_FAILED";

// Shop Page
export const HTTP_SHOP_FETCHING = "HTTP_SHOP_FETCHING";
export const HTTP_SHOP_SUCCESS = "HTTP_SHOP_SUCCESS";
export const HTTP_SHOP_FAILED = "HTTP_SHOP_FAILED";

export const SHOP_UPDATE_ORDER = "SHOP_UPDATE_ORDER";
export const SHOP_UPDATE_PAYMENT = "SHOP_UPDATE_PAYMENT";

// Error Code
export const E_PICKER_CANCELLED = "E_PICKER_CANCELLED";
export const E_PICKER_CANNOT_RUN_CAMERA_ON_SIMULATOR =
  "E_PICKER_CANNOT_RUN_CAMERA_ON_SIMULATOR";
export const E_PERMISSION_MISSING = "E_PERMISSION_MISSING";
export const E_PICKER_NO_CAMERA_PERMISSION = "E_PICKER_NO_CAMERA_PERMISSION";
export const E_USER_CANCELLED = "E_USER_CANCELLED";
export const E_UNKNOWN = "E_UNKNOWN";
export const E_DEVELOPER_ERROR = "E_DEVELOPER_ERROR";
export const TIMEOUT_NETWORK = "ECONNABORTED"; // request service timeout
export const NOT_CONNECT_NETWORK = "NOT_CONNECT_NETWORK";

//////////////// Localization Begin ////////////////
export const NETWORK_CONNECTION_MESSAGE =
  "Cannot connect to server, Please try again.";
export const NETWORK_TIMEOUT_MESSAGE =
  "A network timeout has occurred, Please try again.";
export const UPLOAD_PHOTO_FAIL_MESSAGE =
  "An error has occurred. The photo was unable to upload.";

// export const apiUrl = "http://localhost:8080/br_api/";
// export const apiUrl = "http://192.200.9.106:8080/br_api/";
export const apiUrl = `${process.env.REACT_APP_API_URL}/br_api/`;
export const imageUrl = "http://localhost:8080";

export const server = {
  HTTP_LOGIN_URL: `api_auth/login`,
  COMPANY_URL: `api_data/company`,
  COMPANYWITHCONODIVI_URL: `api_data/companywithconodivi`,
  BU_URL: `api_data/bu`,
  WAREHOUSE_URL: `api_data/warehouse`,
  DEPARTMENT_URL: `api_data/department`,
  COSTCENTER_URL: `api_data/costcenter`,
  APPROVE_URL: `api_data/approve`,
  BUYER_URL: `api_data/buyer`,
  ITEM_URL: `api_data/item`,
  ITEMDETAIL_URL: `api_data/itemdetail`,
  ITEMUNIT_URL: `api_data/itemunit`,
  PHGROUP_URL: `api_data/phgroup`,
  PHBUYER_URL: `api_data/phbuyer`,
  SUPPLIER_URL: `api_data/supplier`,
  PRNUMBER_URL: `api_data/prnumber`,
  PRNUMBERBUYER_URL: `api_data/prnumberbuyer`,
  PRHEAD_URL: `api_data/prhead`,
  PRHEADAPPROVE_URL: `api_data/prheadapprove`,
  PRDETAIL_URL: `api_data/prdetail`,
  PRCONFIRMDETAIL_URL: `api_data/prconfirmdetail`,
  PRDETAILAPPROVE_URL: `api_data/prdetailapprove`,
  PRDETAILBUYER_URL: `api_data/prdetailbuyer`,
  PRCONFIRMBUYER_URL: `api_data/prconfirmbuyer`,
  PRAPPROVE_URL: `api_data/prapprove`,
  CHECKPRAPPROVE_URL: `api_data/checkprapprove`,
  PRREJECT_URL: `api_data/prreject`,
  PRNUMBERWITHOUTUSER_URL: `api_data/prnumberwithoutuser`,
  PRNUMBERUSER_URL: `api_data/prnumberuser`,
  COSTCENTERWITHOUTDEPARTMENT_URL: `api_data/costcenterwithoutdepartment`,
  MONTH_URL: `api_data/month`,
  STATUS_URL: `api_data/status`,
  PRHEADMONITORING_URL: `api_data/prheadmonitoring`,
  PRDETAILMONITORING_URL: `api_data/prdetailmonitoring`,
  PRAPPROVEFINAL_URL: `api_data/prapprovefinal`,

  REFRESH_TOKEN_URL: `refresh/token`,
  REGISTER_URL: `register`,
  PRODUCT_URL: `product`,
  TRANSACTION_URL: `transaction`,
  REPORT_URL: `report`,
  TOKEN_KEY: `token`,
  APPROVE_TOKEN_KEY: `approve_token`,
  REFRESH_TOKEN_KEY: `refresh_token`,
};
